{
 "title": "Smart Meter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Importing Now",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"import_now\") FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas' GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Import Reading",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"import_cumulative\") FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas' "
    }
   ]
  },
  {
   "title": "Exporting Now",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"export_now\") FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas' GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Export Reading",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"export_cumulative\") FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas' "
    }
   ]
  },
  {
   "title": "Current Import Price per Unit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"import_unit_cost\") FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas' "
    }
   ]
  },
  {
   "title": "Mean Import Price per Unit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"import_unit_cost\") FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas' "
    }
   ]
  },
  {
   "title": "Current Export Price per Unit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"export_unit_cost\") FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas' "
    }
   ]
  },
  {
   "title": "Mean Export Price per Unit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"export_unit_cost\") FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas' "
    }
   ]
  },
  {
   "title": "Import in Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"import_cumulative\") - first(\"import_cumulative\") FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas' "
    }
   ]
  },
  {
   "title": "Energy Import Cost in Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"import_cost\") AS total_cost FROM (SELECT non_negative_difference(max(\"import_cumulative\")) * mean(\"import_unit_cost\")AS \"import_cost\" FROM \"Systemstats\".\"autogen\".\"smart_meter\"  GROUP BY time(5m))\nWHERE $timeFilter AND \"fueltype\" != 'gas' "
    }
   ]
  },
  {
   "title": "Export in Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"export_cumulative\") - first(\"export_cumulative\") FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas' "
    }
   ]
  },
  {
   "title": "Energy Export Income in Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"export\") as \"export_revenue\" FROM (SELECT non_negative_difference(max(\"export_cumulative\")) * max(\"export_unit_cost\") AS \"export\" FROM \"Systemstats\".\"autogen\".\"smart_meter\" GROUP BY time(5m)) WHERE $timeFilter AND \"fueltype\" != 'gas' "
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Energy Import",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "SELECT non_negative_difference(max(\"import_cumulative\")) AS \"import\" FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas' GROUP BY time(5m) FILL(null)"
    }
   ]
  },
  {
   "title": "Energy Export",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "SELECT non_negative_difference(max(\"export_cumulative\")) AS \"export\" FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas'  GROUP BY time(5m) FILL(null)"
    }
   ]
  },
  {
   "title": "Energy Import Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "SELECT non_negative_difference(max(\"import_cumulative\")) * mean(\"import_unit_cost\")AS \"import_cost\" FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas' GROUP BY time(5m) FILL(null)"
    },
    {
     "query": "SELECT mean(\"import_unit_cost\")AS \"Unit Price\" FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas'  GROUP BY time(5m) FILL(null)"
    }
   ]
  },
  {
   "title": "Energy Export Income",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "SELECT non_negative_difference(max(\"export_cumulative\")) * max(\"export_unit_cost\") AS \"export\" FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas'  GROUP BY time(5m) FILL(null)"
    },
    {
     "query": "SELECT max(\"export_unit_cost\") AS \"export unit price\" FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas'  GROUP BY time(5m) FILL(null)"
    }
   ]
  },
  { "title": "Daily Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Daily Import",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "SELECT max(\"import_day\") AS \"import\" FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas'  GROUP BY time(1d) FILL(null) "
    }
   ]
  },
  {
   "title": "Daily Export",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "SELECT max(\"export_cumulative\") - min(\"export_cumulative\") AS \"export\" FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas'  GROUP BY time(1d) FILL(null) "
    }
   ]
  },
  {
   "title": "Energy Import Costs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "select sum(\"import_cost\") AS \"usage\" FROM (SELECT non_negative_difference(max(\"import_cumulative\")) * mean(\"import_unit_cost\")AS \"import_cost\" FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas'  GROUP BY time(5m) FILL(null)) GROUP BY time(1d)"
    },
    {
     "query": "SELECT max(\"import_standing_charge\") AS \"standing charge\" FROM \"Systemstats\".\"autogen\".\"smart_meter\" WHERE $timeFilter AND \"fueltype\" != 'gas'  GROUP BY time(1d) FILL(null)"
    }
   ]
  }
 ]
}