{
 "title": "Aquarium",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Filter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"aquarium-filter-pump\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  |> map(fn: (r) => ({Device: r.host, \n     _state: if r._value > 9 then\n        1\n      else\n        0\n  }))\n\n  \n"
    }
   ]
  },
  {
   "title": "Aquarium Light",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"aquarium-light\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  |> map(fn: (r) => ({Device: r.host, \n     _state: if r._value > 15 then\n        1\n      else\n        0\n  }))\n\n  \n"
    }
   ]
  },
  {
   "title": "Surface Skimmer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"aquarium-surface-skimmer\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  |> map(fn: (r) => ({Device: r.host, \n     _state: if r._value > 5 then\n        1\n      else\n        0\n  }))\n\n  \n"
    }
   ]
  },
  {
   "title": "Fluval Heater",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"aquarium-fluval-heater\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  |> map(fn: (r) => ({Device: r.host, \n     _state: if r._value > 100 then\n        1\n      else\n        0\n  }))\n\n  \n"
    }
   ]
  },
  {
   "title": "Integral Heater",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"aquarium-integral-heater\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  |> map(fn: (r) => ({Device: r.host, \n     _state: if r._value > 100 then\n        1\n      else\n        0\n  }))\n\n  \n"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"aquarium\")\n  |> filter(fn: (r) => r._field == \"water_temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n"
    }
   ]
  },
  {
   "title": "Filter Flow Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"aquarium\")\n  |> filter(fn: (r) => r._field == \"flow_mean\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  "
    }
   ]
  },
  {
   "title": "Water Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"aquarium\")\n  |> filter(fn: (r) => r._field == \"water_temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n"
    }
   ]
  },
  {
   "title": "Filter Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "query": "data = from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"aquarium\")\n  |> filter(fn: (r) => r._field == \"flow_mean\" or \n                       r._field == \"flow_max\" or \n                       r._field == \"flow_min\")\n  \ndata\n  |> filter(fn: (r) => r._field == \"flow_mean\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"mean\")\n\ndata\n  |> filter(fn: (r) => r._field == \"flow_max\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n  |> yield(name: \"max\")  \n\ndata\n  |> filter(fn: (r) => r._field == \"flow_min\")\n  |> aggregateWindow(every: v.windowPeriod, fn: min)\n  |> yield(name: \"min\")  "
    }
   ]
  },
  { "title": "Power Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Fluval Heater Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"aquarium-fluval-heater\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n\n  \n"
    }
   ]
  },
  {
   "title": "Integral Heater Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"aquarium-integral-heater\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n\n  \n"
    }
   ]
  },
  {
   "title": "Tank Light Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"aquarium-light\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n\n  \n"
    }
   ]
  },
  {
   "title": "Surface Skimmer Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"aquarium-surface-skimmer\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n\n  \n"
    }
   ]
  },
  {
   "title": "Filter Pump power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"aquarium-filter-pump\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n\n  \n"
    }
   ]
  },
  {
   "title": "Total Tank Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Systemstats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power_watts\")\n  |> filter(fn: (r) => r._field == \"consumption\")\n  |> filter(fn: (r) => r.host == \"aquarium-filter-pump\" or\n                       r.host == \"aquarium-light\" or\n                       r.host == \"aquarium-surface-skimmer\" or\n                       r.host == \"aquarium-fluval-heater\" or\n                       r.host == \"aquarium-integral-heater\"\n                       )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  // Collapse into a  single time aligned group\n  |> group()\n  // Add it all up\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\n                       \n                       "
    }
   ]
  }
 ]
}